
package ticket.testclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Ticket", targetNamespace = "http://hw2.flightticketreservation/ticket.service/ticket", wsdlLocation = "http://localhost:8080/TicketService/ticket?wsdl")
@HandlerChain(file = "Ticket_Service_handler.xml")
public class Ticket_Service
    extends Service
{

    private final static URL TICKET_WSDL_LOCATION;
    private final static WebServiceException TICKET_EXCEPTION;
    private final static QName TICKET_QNAME = new QName("http://hw2.flightticketreservation/ticket.service/ticket", "Ticket");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TicketService/ticket?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKET_WSDL_LOCATION = url;
        TICKET_EXCEPTION = e;
    }

    public Ticket_Service() {
        super(__getWsdlLocation(), TICKET_QNAME);
    }

    public Ticket_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKET_QNAME, features);
    }

    public Ticket_Service(URL wsdlLocation) {
        super(wsdlLocation, TICKET_QNAME);
    }

    public Ticket_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKET_QNAME, features);
    }

    public Ticket_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ticket_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketService
     */
    @WebEndpoint(name = "TicketPort")
    public TicketService getTicketPort() {
        return super.getPort(new QName("http://hw2.flightticketreservation/ticket.service/ticket", "TicketPort"), TicketService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketService
     */
    @WebEndpoint(name = "TicketPort")
    public TicketService getTicketPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hw2.flightticketreservation/ticket.service/ticket", "TicketPort"), TicketService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKET_EXCEPTION!= null) {
            throw TICKET_EXCEPTION;
        }
        return TICKET_WSDL_LOCATION;
    }

}
