
package itinerary.testclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Itinerary", targetNamespace = "http://hw2.flightticketreservation/itinerary.service/itinerary", wsdlLocation = "http://localhost:8080/ItineraryService/itinerary?wsdl")
@HandlerChain(file = "Itinerary_Service_handler.xml")
public class Itinerary_Service
    extends Service
{

    private final static URL ITINERARY_WSDL_LOCATION;
    private final static WebServiceException ITINERARY_EXCEPTION;
    private final static QName ITINERARY_QNAME = new QName("http://hw2.flightticketreservation/itinerary.service/itinerary", "Itinerary");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ItineraryService/itinerary?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITINERARY_WSDL_LOCATION = url;
        ITINERARY_EXCEPTION = e;
    }

    public Itinerary_Service() {
        super(__getWsdlLocation(), ITINERARY_QNAME);
    }

    public Itinerary_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITINERARY_QNAME, features);
    }

    public Itinerary_Service(URL wsdlLocation) {
        super(wsdlLocation, ITINERARY_QNAME);
    }

    public Itinerary_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITINERARY_QNAME, features);
    }

    public Itinerary_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Itinerary_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItineraryService
     */
    @WebEndpoint(name = "ItineraryPort")
    public ItineraryService getItineraryPort() {
        return super.getPort(new QName("http://hw2.flightticketreservation/itinerary.service/itinerary", "ItineraryPort"), ItineraryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItineraryService
     */
    @WebEndpoint(name = "ItineraryPort")
    public ItineraryService getItineraryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hw2.flightticketreservation/itinerary.service/itinerary", "ItineraryPort"), ItineraryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITINERARY_EXCEPTION!= null) {
            throw ITINERARY_EXCEPTION;
        }
        return ITINERARY_WSDL_LOCATION;
    }

}
