
package itinerary.testclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItineraryService", targetNamespace = "http://hw2.flightticketreservation/itinerary.service/itinerary")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItineraryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns itinerary.testclient.Itinerary
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItinerary", targetNamespace = "http://hw2.flightticketreservation/itinerary.service/itinerary", className = "itinerary.testclient.FindItinerary")
    @ResponseWrapper(localName = "findItineraryResponse", targetNamespace = "http://hw2.flightticketreservation/itinerary.service/itinerary", className = "itinerary.testclient.FindItineraryResponse")
    @Action(input = "http://hw2.flightticketreservation/itinerary.service/itinerary/ItineraryService/findItineraryRequest", output = "http://hw2.flightticketreservation/itinerary.service/itinerary/ItineraryService/findItineraryResponse")
    public Itinerary findItinerary(
        @WebParam(name = "arg0", targetNamespace = "")
        Flight arg0);

}
